name: Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Node.js Application
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Code
        uses: actions/checkout@v2

      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
        set -e  # Exit immediately if a command exits with a non-zero status
        echo "Changing directory..."
        cd /home/ec2-user/serengetiboard_backend || exit 1
        echo "Pulling latest code from git..."
        git pull origin main || exit 1
        echo "Installing dependencies..."
        npm install || exit 1
        echo "Restarting application..."
        npm restart || exit 1
        echo "Commands executed successfully."
        exit
        EOF
